# PART 1 -  FEATURE ENGINEERING
pacman::p_load(tidyverse,
               timetk,
               tsibble,
               tsibbledata,
               fastDummies,
               skimr, 
               tidymodels)

# inspiration
# https://blog.bguarisma.com/time-series-forecasting-lab-part-2-feature-engineering-with-recipes

#---- Params

# poblacion


# Data
# Let us load the Australian retail trade turnover dataset tsibble::aus_retail . 
# The time series measure is Turnover which represents the retail turnover in $Million AUD.
# Our final goal is to forecast Turnover for the next year.
# Within the dataset each series is uniquely identified using two keys:
# -State: The Australian state (or territory)
# -Industry: The industry of retail trade
# We will focus on the “Australian Capital Territory” State value only and use all Industry values.

monthly_retail_tbl <- tsibbledata::aus_retail %>%
  tk_tbl() %>%
  filter(State == "Australian Capital Territory") %>%
  mutate(Month = as.Date(Month)) %>%
  mutate(Industry = as_factor(Industry)) %>%
  select(Month, Industry, Turnover)

# first feature engineered tibble groups_fe_tbl
Industries <- unique(monthly_retail_tbl$Industry)

groups <- lapply(X = 1:length(Industries), FUN = function(x){
  
  monthly_retail_tbl %>%
    filter(Industry == Industries[x]) %>%
    arrange(Month) %>%
    # Measure Transformation: variance reduction with Log(x+1)
    mutate(Turnover =  log1p(x = Turnover)) %>%
    # Measure Transformation: standardization
    mutate(Turnover =  standardize_vec(Turnover)) %>%
    # Calendar-based features. This function adds 25+ time series features.
    tk_augment_timeseries_signature(.date_var = Month) %>% 
    # cleaning: suppress redundant and useless columns
    select(-diff, -matches("(.xts$)|(.iso$)|(hour)|(minute)|(second)|(day)|(week)|(am.pm)")) %>%
    # All categorical variables can be dummyfied,
    dummy_cols(select_columns = c("month.lbl")) %>%
    select(-month.lbl) %>%
    # We must normalize index.num and year columns, 
    mutate(index.num = normalize_vec(x = index.num)) %>%
    mutate(year = normalize_vec(x = year)) %>%
    future_frame(Month, .length_out = "12 months", .bind_data = TRUE) %>%
    mutate(Industry = Industries[x]) %>%
    tk_augment_fourier(.date_var = Month, .periods = 12, .K = 1) %>%
    tk_augment_lags(.value = Turnover, .lags = 12) %>%
    tk_augment_slidify(.value   = Turnover_lag12,
                       .f       = ~ mean(.x, na.rm = TRUE), 
                       .period  = c(3, 6, 9, 12),
                       .partial = TRUE,
                       .align   = "center")
})

groups_fe_tbl <- bind_rows(groups) %>%
  rowid_to_column(var = "rowid")


# Save standarization parameters
# Since we are working with panel data (there are 20 time series, one for each Industry), 
# consequently there will be 20 Standardization Parameters (mean, standard deviation) 
# generated by standardize_vec(Turnover).

tmp <- monthly_retail_tbl %>%
  group_by(Industry) %>% 
  arrange(Month) %>%
  mutate(Turnover = log1p(x = Turnover)) %>% 
  group_map(~ c(mean = mean(.x$Turnover, na.rm = TRUE),
                sd = sd(.x$Turnover, na.rm = TRUE))) %>% 
  bind_rows()
std_mean <- tmp$mean
std_sd <- tmp$sd
rm('tmp')

